/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ModuloProfesores;

import Administrador.ActualizarProfe;
import static Administrador.AdminProfesores.contadorProfesores;
import static Administrador.AdminProfesores.fila;
import static Administrador.AdminProfesores.nombre;
import static Administrador.AdminProfesores.profesores;
import static Administrador.AdministradorCursos.contadorCursos;
import static Administrador.AdministradorCursos.cursos;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import java.io.FileReader;
import java.util.Arrays;
import java.io.BufferedReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import proyecto1.Login;
import static proyecto1.Login.codigoLog;

/**
 *
 * @author andre
 */
public class Inicio extends javax.swing.JFrame {
    
    public static String codigo;
    public static String nombre;
    public static String apellido;
    public static String correo;
    public static String contrasenia;
    public static String genero;
    public static String codigoCurso;
    public static String nombreCurso;
    public static String creditosCurso;
    public static String alumnosCurso;
    public static String profesorCurso;
    public static int indexProfesor;
    public static int cursoSelec;

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        mostrarCurso();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AdminCursosbtn = new javax.swing.JButton();
        Actualizarbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadoCursos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Cursos asignados");

        AdminCursosbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AdminCursosbtn.setText("Administrar Curso");
        AdminCursosbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminCursosbtnActionPerformed(evt);
            }
        });

        Actualizarbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Actualizarbtn.setText("Actualizar Datos");
        Actualizarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarbtnActionPerformed(evt);
            }
        });

        ListadoCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Creditos", "Alumno", "Profesor"
            }
        ));
        jScrollPane1.setViewportView(ListadoCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AdminCursosbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(80, 80, 80)
                        .addComponent(Actualizarbtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Actualizarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(AdminCursosbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminCursosbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminCursosbtnActionPerformed
        // TODO add your handling code here:
        cursoSelec = ListadoCursos.getSelectedRow();
        
        codigoCurso = ListadoCursos.getModel().getValueAt(fila, 0).toString();
        nombreCurso = ListadoCursos.getModel().getValueAt(fila, 1).toString();
        creditosCurso = ListadoCursos.getModel().getValueAt(fila, 3).toString();
        alumnosCurso = ListadoCursos.getModel().getValueAt(fila, 2).toString();
        profesorCurso = ListadoCursos.getModel().getValueAt(fila, 4).toString();
        
        this.setVisible(false);
        CursoProfesor ap = new CursoProfesor();
        ap.setVisible(true);
    }//GEN-LAST:event_AdminCursosbtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        this.setVisible(false);
        Login ap = new Login();
        ap.setVisible(true);
    }//GEN-LAST:event_formWindowClosing

    private void ActualizarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarbtnActionPerformed
        // TODO add your handling code here:
        
        for(indexProfesor=0; indexProfesor<contadorProfesores; indexProfesor++){
            if(codigoLog.equals(profesores[indexProfesor].codigo)){
                codigo=profesores[indexProfesor].codigo;
                nombre=profesores[indexProfesor].nombre;
                apellido=profesores[indexProfesor].apellido;
                correo=profesores[indexProfesor].correo;
                contrasenia=profesores[indexProfesor].contrasenia;
                genero=profesores[indexProfesor].genero;
                
                fila=indexProfesor;
                
                ActualizarDatos ap = new ActualizarDatos();
                ap.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_ActualizarbtnActionPerformed

    public void mostrarCurso(){
        for(int i=0; i<contadorCursos;i++){
            int j=0;
            if(codigoLog.equals(cursos[i].profesor)){
                DefaultTableModel modeloListado = (DefaultTableModel) ListadoCursos.getModel();
                
                modeloListado.setValueAt(cursos[i].codigo, j, 0);
                modeloListado.setValueAt(cursos[i].nombre, j, 1);
                modeloListado.setValueAt(cursos[i].creditos, j, 2);
                modeloListado.setValueAt(cursos[i].alumnos, j, 3);
                modeloListado.setValueAt(cursos[i].profesor, j, 4);
                j++;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizarbtn;
    private javax.swing.JButton AdminCursosbtn;
    private javax.swing.JTable ListadoCursos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
